### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by PeteManchester** [bazwilliams/upnp-playlist-service#3]
What format should my PlayLists be, I have .m3u playlists that have the full path to the files, these work in MinimServer

```
F:\ServerFolders\Music\iTunes\iTunes Media\Music\Green Day\American Idiot\01 American Idiot.mp3
F:\ServerFolders\Music\iTunes\iTunes Media\Music\Siouxsie & the Banshees\Once Upon A Time-The Singles\1-08-Israel.mp3
F:\ServerFolders\Music\iTunes\iTunes Media\Music\The Sex Pistols\Never Mind the Bollocks\10 Pretty Vacant.mp3
F:\ServerFolders\Music\iTunes\iTunes Media\Music\Razorlight\Razorlight\04 America.m4a
```

When I try to play a playlist the Radio Source is always selected.

When I try to save a currently playing track to a Playlist it is saved as the meta data

```
#<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="0$albums$showaa$alist.0$*a0$*i10325" parentID="0$albums$showaa$alist.0$*a0" restricted="1"><dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">Hurricanes</dc:title><upnp:genre xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">Rock</upnp:genre><dc:date xmlns:dc="http://purl.org/dc/elements/1.1/">2012-01-01</dc:date><upnp:album xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">#3</upnp:album><upnp:artist role="AlbumArtist" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">The Script</upnp:artist><upnp:artist xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">The Script</upnp:artist><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">The Script</dc:creator><upnp:originalTrackNumber xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">12</upnp:originalTrackNumber><upnp:albumArtURI dlna:profileID="JPEG_LRG" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">http://192.168.1.205:9790/minimserver/*/Music/The*20Script/*233/-12-Hurricanes.mp3/$!picture-34-45216.jpg</upnp:albumArtURI><res duration="0:04:38.752" size="11829248" bitrate="40000" sampleFrequency="44100" nrAudioChannels="2" protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000">http://192.168.1.205:9790/minimserver/*/Music/The*20Script/*233/-12-Hurricanes.mp3</res><upnp:class xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">object.item.audioItem.musicTrack</upnp:class></item></DIDL-Lite>
```

Maybe it's something I've done wrong with the config.

In the Config file I tried various things, but this is the one i use at the moment, I set the rootMusic to '.' because I have the full path in the playlists.

```
var config = {};

// Unix locations
//config.musicRoot = '/mnt/media/music';
//config.playlistPath = '/mnt/media/music/Playlists';

// Windows locations
config.musicRoot = '.';
config.playlistPath = 'F:\\ServerFolders\\Music\\PlayLists';

module.exports = config;
```

I'm running on WiHS 2011 on which h MinimServer  also runs.

Thanks,

Pete.

**Comment by bazwilliams** [comment]
Thanks for trying this out and the feedback!

Unfortunately, this app won't load an existing m3u file into a Upnp device, you'll need to use a fully featured control point and minimserver to do that. It can only load in DIDLite metadata stored in the comments. 

The service was originally designed to extract a playlist that is already on the media player into an m3u file reverse engineering the Uri (generated by minim) into a relative file path. To take advantage of this you'd need to set up the `config.musicRoot` to be `F:\\ServerFolders\\Music`. 

When Linn introduced Tidal support I wanted to be able to create playlists with Tidal tracks alongside my own studio masters. So I modified the code to also include the DIDLite metadata alongside the filepath if it could generate one. 

You'll need to load your existing m3u file using Kazoo, then save it back out using this service which will include a link to the music file (if found) and the metadata. Once saved by the service, you can play it back via the service. 

Also once created you'll be able to use the 'add currently playing track' feature to build up playlists from any device playing music. 

As for the radio issue, I haven't had that problem here - but I have assumed the radio source Id is always 1 which I'm sure is the problem. I've created a separate issue #4 for this and try to recreate here.

**Comment by PeteManchester** [comment]
Thanks Barry,

I set my config.musicRoot as you said and it works..

Really good..

I have some suggestions for some functionality but appreciate that you can't do everything..

Is it possible to add a startup volume on the Wake Up alarm.

Also could the volume ramp up on Wake up, from zreo to the scheduled volume.

Also can you add a shuffle track flag to the schedule, so that you don't always wake up to the same track from the playlist.

I've got some of the above in my Alarm Plugin, but don't have the nice web page that you have.

Another idea, could you add navigation between your Playlist and Devices web pages, so that you can easily navigate between two..

As I say only some ideas and appreciate how much work you have already done on this..

Cheers,

Pete.

**Comment by bazwilliams** [comment]
Hi Pete,

Glad you've got it working! I'll probably need to update the readme to make it clearer. 

Thanks for your suggestions. Good news is that many of these are already implemented in the RESTful api which I use for my RCU/home automation service. We have a switch in our bathroom which triggers preset playlists to load into the ds in shuffle mode and has buttons for volume. 

I just need to add them to the way schedules are stored and the ui.

Keep the suggestions coming!

**Comment by bazwilliams** [comment]
Quick plug for my blog post about the switch:
http://blog.bjw.me.uk/2015/01/linn-ds-homebrew-rcu-with-playlist.html

**Comment by bazwilliams** [comment]
Volume ramp added as issue #5 
Shuffle added as issue #6 
Link between Playlist and Alarm pages added as issue #7

**Comment by bazwilliams** [comment]
Readme updated as part of 5f1c422631ad795885da5709166ca494256dc631

Closing as new issues created.
